// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAugN2rLQcBd17GfRYwyP3hAwByzvXqIpc',
    appId: '1:462328158002:web:e5a2f3f963a23b90f0a92b',
    messagingSenderId: '462328158002',
    projectId: 'mymarket-app-bb73c',
    authDomain: 'mymarket-app-bb73c.firebaseapp.com',
    storageBucket: 'mymarket-app-bb73c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMDqWBVYzsv-Ji27ffdxMh1uQbwBGmKls',
    appId: '1:462328158002:android:7f10eb60795bbd7ff0a92b',
    messagingSenderId: '462328158002',
    projectId: 'mymarket-app-bb73c',
    storageBucket: 'mymarket-app-bb73c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5LRiYbCqqycytC0lIG7oOHSHWKOHKKow',
    appId: '1:462328158002:ios:17bdf7905f65661af0a92b',
    messagingSenderId: '462328158002',
    projectId: 'mymarket-app-bb73c',
    storageBucket: 'mymarket-app-bb73c.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceMhs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5LRiYbCqqycytC0lIG7oOHSHWKOHKKow',
    appId: '1:462328158002:ios:17bdf7905f65661af0a92b',
    messagingSenderId: '462328158002',
    projectId: 'mymarket-app-bb73c',
    storageBucket: 'mymarket-app-bb73c.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceMhs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAugN2rLQcBd17GfRYwyP3hAwByzvXqIpc',
    appId: '1:462328158002:web:fdf125c36475e0e2f0a92b',
    messagingSenderId: '462328158002',
    projectId: 'mymarket-app-bb73c',
    authDomain: 'mymarket-app-bb73c.firebaseapp.com',
    storageBucket: 'mymarket-app-bb73c.firebasestorage.app',
  );
}
